### ISSUE TITLE
src.zip

### ISSUE THREAD

**Issue by daveyostcom** [openjfx/openjfx.github.io#18]
https://gluonhq.com/products/javafx/ should have download links to all the src.zip versions or at least a link to where they can be found.

https://openjfx.io/openjfx-docs/ page should show how to set up IDEs for javafx src.zip and javafx online documentation.

**Comment by abhinayagarwal** [comment]
`src.zip` is bundled with the SDK and some IDEs have problem loading the same. This is a known issue and should be automatically resolved once the location of `src.zip` is changed in the SDK: https://bugs.openjdk.java.net/browse/JDK-8258499
