### ISSUE TITLE
Adding ValidatorFX to Community section

### ISSUE THREAD

**Issue by effad** [openjfx/openjfx.github.io#29]
Having presented ValidatorFX at the JFX days 2020 (online conference) I would like to add it to the Community Section of https://openjfx.io.
Would a PR for this be acceptable? If yes, is there a HOWTO for working with the contents of the develop branch of this repo? I've already cloned it and installed hugo. But what next?
=> Maybe there should be a CONTRIBUTING.md in the repo?

**Comment by eugener** [comment]
Thank you!
