### ISSUE TITLE
On the Mac OS, Menubar sets setUseSystemMenubar (true); after starting the app, menu can't be clicked (clicking doesn't respond), You need to switch to other applications and return to the current application again to click normally(Click to respond)

### ISSUE THREAD

**Issue by shenzhenMirren** [openjfx/openjfx.github.io#35]
On the Mac OS, Menubar sets setUseSystemMenubar (true); after starting the app, menu can't be clicked (clicking doesn't respond), You need to switch to other applications and return to the current application again to click normally(Click to respond)

my os
<img width="586" alt="QQ20210228-210310@2x" src="https://user-images.githubusercontent.com/24805209/109419445-6eab9e00-7a08-11eb-84f8-1d979eb729b1.png">

java version 11.0.10  javafx version 13

video
https://user-images.githubusercontent.com/24805209/109419449-75d2ac00-7a08-11eb-87ac-b109633e38c9.mp4

**Comment by abhinayagarwal** [comment]
This is not the right place to log issues for the JavaFX platform. Please discuss the issue on the [openjfx-dev mailing list](https://mail.openjdk.java.net/pipermail/openjfx-dev/).
