### ISSUE TITLE
Website not loading with www prefix

### ISSUE THREAD

**Issue by danielpeintner** [openjfx/openjfx.github.io#44]
The _hosted_ website is always referred to as https://openjfx.io and doings so works fine.

It happened to me to type in the URL manually (since I know the domain) and I typed www.openjfx.io.
Having said that, **with** the `www` prefix it does not load.

I assume this is just a configuration option that can fix that problem.

This might be a non-issue (please close issue if you think so).

**Comment by eugener** [comment]
Since there was no intention to support `www` prefix originally,  I'm closing this issue. 
But please feel free to reopen it if  you see any significant benefits in having that prefix.
