### ISSUE TITLE
JavaFX 19 API docs page gives a 404

### ISSUE THREAD

**Issue by kevinrushforth** [openjfx/openjfx.github.io#62]
The JavaFX 19 API docs URL, which is linked from [openjfx.io](https://openjfx.io/), gives a 404:

https://openjfx.io/javadoc/19/

**Comment by tiainen** [comment]
Thanks for the report. The actual work is being worked on here: https://github.com/openjfx/javadoc/issues/20

**Comment by kevinrushforth** [comment]
Good to know. Thanks.

**Comment by tiainen** [comment]
The docs have been put online.
